version: '3.1'

services:
  db:
    image: mavinyehdocker/stockdb:1.0 
    environment:
      MYSQL_ROOT_PASSWORD: guoke618
    ports:
      - 3306:3306
    volumes:
      - /usr/shigure/data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080

